# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8dad77f5eacfc3164b5647063947ce38b01f8a0bcdcacf53e7649cfafb38489badbc5f3f1dea2509f56f6082ca30a9ec4190d2c6ee90b86dc91c975c420ac8c3

test:
  secret_key_base: 4421aaffdbefc56329733bc689378c39a94d2b2f14c0352dd1beea68deafa99139ca984826f0af3441d824c8cca585d8f95a3ad1ac9870487980a87624f5f95a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>